### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by forensic** [billdawson/ti_coffee_plugin#8]
At least on linux, TitaniumStudio looks in /home/user/.titanium rather than in the titanium install folder.  Despite putting the plugin there and it running partially, I'm getting this error:

[INFO] Building testcoffee for Android ... one moment
[INFO] plugin=/home/f/.titanium/plugins/ti_coffee_plugin/1.0/plugin.py
[INFO] Detected compiler plugin: ti_coffee_plugin/1.0
[INFO] Compiling CoffeeScript files
[DEBUG] Compiling /home/f/TitaniumStudioWorkspace/testcoffee/Resources/app.coffee
[ERROR] Exception occured while building Android project:
[ERROR] Traceback (most recent call last):
[ERROR]   File "/home/f/.titanium/mobilesdk/linux/1.6.2/android/builder.py", line 1646, in <module>
[ERROR]     s.build_and_run(False, avd_id)
[ERROR]   File "/home/f/.titanium/mobilesdk/linux/1.6.2/android/builder.py", line 1307, in build_and_run
[ERROR]     p.compile(compiler_config)
[ERROR]   File "/home/f/.titanium/plugins/ti_coffee_plugin/1.0/plugin.py", line 133, in compile
[ERROR]     build_all_coffee(os.path.join(config['project_dir'], 'Resources'), file_hash_folder)
[ERROR]   File "/home/f/.titanium/plugins/ti_coffee_plugin/1.0/plugin.py", line 125, in build_all_coffee
[ERROR]     if build_coffee(file_path):
[ERROR]   File "/home/f/.titanium/plugins/ti_coffee_plugin/1.0/plugin.py", line 101, in build_coffee
[ERROR]     process = subprocess.Popen(command_args, stdout=subprocess.PIPE, stdin=subprocess.PIPE)
[ERROR]   File "/usr/lib/python2.6/subprocess.py", line 623, in **init**
[ERROR]     errread, errwrite)
[ERROR]   File "/usr/lib/python2.6/subprocess.py", line 1141, in _execute_child
[ERROR]     raise child_exception
[ERROR] OSError: [Errno 2] No such file or directory

**Comment by forensic** [comment]
oops, didn't have coffee installed.
